// Fill out your copyright notice in the Description page of Project Settings.

#include "SideScrollerDelegates.h"
#include "Kismet/GameplayStatics.h"

USideScrollerDelegates::FOnCollectableAdded USideScrollerDelegates::OnCollectableAdded;
USideScrollerDelegates::FOnCollectableWeaponAdded USideScrollerDelegates::OnCollectableWeaponAdded;
USideScrollerDelegates::FOnCollectableCoinAdded USideScrollerDelegates::OnCollectableCoinAdded;
USideScrollerDelegates::FOnCollectableHealthAdded USideScrollerDelegates::OnCollectableHealthAdded;
USideScrollerDelegates::FOnPlayerAddHealth USideScrollerDelegates::OnPlayerAddHealth;
USideScrollerDelegates::FOnPlayerChangeHealth USideScrollerDelegates::OnPlayerChangeHealth;
USideScrollerDelegates::FOnPlayerChangeCoins USideScrollerDelegates::OnPlayerChangeCoins;
USideScrollerDelegates::FOnShowWidget USideScrollerDelegates::OnShowWidget;
USideScrollerDelegates::FOnInitFirstWidget USideScrollerDelegates::OnInitFirstWidget;
USideScrollerDelegates::FOnStartNewGame USideScrollerDelegates::OnStartNewGame;
USideScrollerDelegates::FOnPlayerDied USideScrollerDelegates::OnPlayerDied;
USideScrollerDelegates::FOnShowHighscore USideScrollerDelegates::OnShowHighscore;
USideScrollerDelegates::FOnStartNewLevel USideScrollerDelegates::OnStartNewLevel;
USideScrollerDelegates::FOnRestartAtLastCheckpoint USideScrollerDelegates::OnRestartAtLastCheckpoint;
USideScrollerDelegates::FOnGameWon USideScrollerDelegates::OnGameWon;
USideScrollerDelegates::FOnOpenIngameMenu USideScrollerDelegates::OnOpenIngameMenu;
USideScrollerDelegates::FOnCloseIngameMenu USideScrollerDelegates::OnCloseIngameMenu;
USideScrollerDelegates::FOnHudShown USideScrollerDelegates::OnHudShown;
USideScrollerDelegates::FOnResetCombo USideScrollerDelegates::OnResetCombo;
