// Fill out your copyright notice in the Description page of Project Settings.

#include "SideScrollerDelegates.h"
#include "Kismet/GameplayStatics.h"

USideScrollerDelegates::FOnCollectableAdded USideScrollerDelegates::OnCollectableAdded;
USideScrollerDelegates::FOnCollectableWeaponAdded USideScrollerDelegates::OnCollectableWeaponAdded;
USideScrollerDelegates::FOnCollectableCoinAdded USideScrollerDelegates::OnCollectableCoinAdded;
USideScrollerDelegates::FOnCollectableHealthAdded USideScrollerDelegates::OnCollectableHealthAdded;
USideScrollerDelegates::FOnPlayerChangeHealth USideScrollerDelegates::OnPlayerChangeHealth;
USideScrollerDelegates::FOnShowWidget USideScrollerDelegates::OnShowWidget;
USideScrollerDelegates::FOnInitFirstWidget USideScrollerDelegates::OnInitFirstWidget;
USideScrollerDelegates::FOnStartNewGame USideScrollerDelegates::OnStartNewGame;
USideScrollerDelegates::FOnPlayerDied USideScrollerDelegates::OnPlayerDied;
USideScrollerDelegates::FOnShowHighscore USideScrollerDelegates::OnShowHighscore;
USideScrollerDelegates::FOnStartNewLevel USideScrollerDelegates::OnStartNewLevel;
USideScrollerDelegates::FOnRestartCurrentLevel USideScrollerDelegates::OnRestartCurrentLevel;
USideScrollerDelegates::FOnTriggerBoxEnter USideScrollerDelegates::OnTriggerBoxEnter;
USideScrollerDelegates::FOnGameWon USideScrollerDelegates::OnGameWon;
